// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jvpudvlmwefyobflcfjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp2cHVkdmxtd2VmeW9iZmxjZmpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NDEzNTgsImV4cCI6MjA2NTExNzM1OH0.T-7OmNZkcfDTiD3aPVixe8JIeIZ3ZZRrbC0oRjA7d_k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);